---
title: "Analysis"
author: ""
date: "`r Sys.Date()`"
output:
  html_document:
    number_sections: no
    toc: yes
    toc_float: yes
  pdf_document:
    number_sections: no
    toc: yes
---


## Dissentangling climate and parental effects on recruitment of southern stock of European hake


```{r, include=FALSE}
# Load pckgs -------------------------------------------------------------------
library(PerformanceAnalytics)
library(FSA)
library(TSA)
library(FSAdata)
library(dplyr)
library(tidyverse)
library(magrittr)
library(lattice)
library(Publish)
library(sciplot)
library(multcomp)
library(car)
library(knitr)
library(gplots)
library(zoo)
library(fpp2) 
library(tseries)
library(imputeTS)
library(forecast)
library(lmtest)
library(tidymv)
library(ggplot2)
library(GGally)
library(Hmisc)
library(fUnitRoots)
library(itsadug)
library(carData)
library(corrplot)
library(corrgram)
library(DescTools)
library(mgcv)
library(gratia)


# Read data --------------------------------------------------------------------

model<-read.csv("modelo1.csv",header=TRUE,dec=".",sep=";")
model$ssb_val<-as.numeric(model$ssb_val)
model$ssb_low<-as.numeric(model$ssb_low)
model$ssb_upp<-as.numeric(model$ssb_upp)
model$rec_value<-as.numeric(model$rec_value)
model$rec_low<-as.numeric(model$rec_low)
model$rec_upp<-as.numeric(model$rec_upp)
model$L50_females<-as.numeric(model$L50_females)
model$L50_males<-as.numeric(model$L50_males)
model$L50<-as.numeric(model$L50)

# Subset year
model<-subset(model,year >= 1980)
```


## Data exploration (Zuur et al 2010)

```{r, include=FALSE}
# Exploratory plots ------------------------------------------------------------
ggplot(model,aes(x=ssb_val,y=rec_value))+geom_point()+
  geom_smooth(method="loess")+theme_minimal()
ggplot(model,aes(x=L50_females,y=rec_value))+geom_point()+
  geom_smooth(method="loess")+theme_minimal()
ggplot(model,aes(x=shannon_females,y=rec_value))+geom_point()+
  (method="loess")+theme_minimal()
ggplot(model,aes(x=shannon_females_s1,y=rec_value))+geom_point()+
  geom_smooth(method="loess")+theme_minimal()
ggplot(model,aes(x=shannon_females_s2,y=rec_value))+geom_point()+
  geom_smooth(method="loess")+theme_minimal()
ggplot(model,aes(x=shannon_females_s3,y=rec_value))+geom_point()+
  geom_smooth(method="loess")+theme_minimal()
ggplot(model,aes(x=shannon_females_s4,y=rec_value))+geom_point()+
  geom_smooth(method="loess")+theme_minimal()
ggplot(model,aes(x=sst,y=rec_value))+geom_point()+
  geom_smooth(method="loess")+theme_minimal()
ggplot(model,aes(x=nao,y=rec_value))+geom_point()+
  geom_smooth(method="loess")+theme_minimal()
ggplot(model,aes(x=amo,y=rec_value))+geom_point()+
  geom_smooth(method="loess")+theme_minimal()

vars<-c("rec_value","ssb_val","L50_females","shannon_females","shannon_females_s1", "shannon_females_s2", "shannon_females_s3", "shannon_females_4","sst","nao","amo")
  par(mfrow = c(2, 3))  # Layout for multiple boxplots
  for (v in vars) {
  boxplot(model[[v]], main = v)
  }

# NA´s
sst<-na.omit(model$sst)
L50_females<-na.omit(model$L50_females)
shannon_females<-na.omit(model$shannon_females)

# Outliers ---------------------------------------------------------------------
tsoutliers::tso(ts(model$ssb_val,start=1980))
  #plot(tsoutliers::tso(ts(model$rec_value,start=1980)))
tsoutliers::tso(ts(model$sst,start=1980))
tsoutliers::tso(ts(model$nao,start=1980)) 
tsoutliers::tso(ts(model$amo,start=1980))
tsoutliers::tso(ts(model$L50_females,start=1980))
tsoutliers::tso(ts(model$shannon_females,start=1980))
tsoutliers::tso(ts(model$shannon_females_s1,start=1980))
tsoutliers::tso(ts(model$shannon_females_s2,start=1980))
tsoutliers::tso(ts(model$shannon_females_s3,start=1980))
tsoutliers::tso(ts(model$shannon_females_s4,start=1980))

  # Clean data
outlier_years_rec_value<-c(1989,2005,2007,2023)
outlier_years_nao<-2010
outlier_years_L50<-1997
outlier_years_L50_males<-2021
outlier_years_shannon<-c(1994,2005)
outlier_years_shannon_females<-c(1994,2005)
outlier_years_shannon_females_s1<-1994
outlier_years_shannon_females_s2<-1994
outlier_years_shannon_females_s3<-2006
outlier_years_shannon_females_s4<-2005

model_clean<-model
model_clean$rec_value[model_clean$year %in% outlier_years_rec_value]<-NA
model_clean$nao[model_clean$year == outlier_years_nao]<-NA
model_clean$L50[model_clean$year == outlier_years_L50]<-NA
model_clean$L50_males[model_clean$year == outlier_years_L50_males]<-NA
model_clean$shannon[model_clean$year == outlier_years_shannon]<-NA
model_clean$shannon_females[model_clean$year == outlier_years_shannon_females]<-NA
model_clean$shannon_females_s1[model_clean$year == outlier_years_shannon_females_s1]<-NA
model_clean$shannon_females_s2[model_clean$year == outlier_years_shannon_females_s2]<-NA
model_clean$shannon_females_s3[model_clean$year == outlier_years_shannon_females_s3]<-NA
model_clean$shannon_females_s4[model_clean$year == outlier_years_shannon_females_s4]<-NA

model<-model_clean
model_clean<-na.omit(model)

# Normality assumption ---------------------------------------------------------
plot(model$ssb_val)
hist(model$ssb_val)
qqnorm(model$ssb_val)
qqline(model$ssb_val,col="red")
shapiro.test(model$ssb_val) 

plot(model$rec_value)
hist(model$rec_value)
qqnorm(model$rec_value)
qqline(model$rec_value,col="red")
shapiro.test(model$rec_value) 

plot(model$L50_females)
hist(model$L50_females)
qqnorm(model$L50_females)
qqline(model$L50_females,col="red")
shapiro.test(model$L50_females) 

plot(model$shannon_females)
hist(model$shannon_females)
qqnorm(model$shannon_females)
qqline(model$shannon_females,col="red")
shapiro.test(model$shannon_females) 
shapiro.test(model$shannon_females_s1) 
shapiro.test(model$shannon_females_s2) 
shapiro.test(model$shannon_females_s3) 
shapiro.test(model$shannon_females_s4) 

plot(model$sst)
hist(model$sst)
qqnorm(model$sst)
qqline(model$sst,col="red")
shapiro.test(model$sst) 

plot(model$nao)
hist(model$nao)
qqnorm(model$nao)
qqline(model$nao,col="red")
shapiro.test(model$nao) 

plot(model$amo)
hist(model$amo)
qqnorm(model$amo)
qqline(model$amo,col="red")
shapiro.test(model$amo) 

# Homocedasticity --------------------------------------------------------------
model_lm<-lm(rec_value~ssb_val,data=model)
plot(model_lm$fitted.values,model_lm$residuals) 
abline(h=0,col="red")
bptest(model_lm)

# Correlation and colineality --------------------------------------------------
numeric_vars<-model_clean[,vars]
cor_matrix<-cor(numeric_vars,use="complete.obs")
round(cor_matrix,2)
par(mfrow=c(1,1))
corrplot::corrplot(cor_matrix,method="circle",type="upper",tl.col="black") 

  # Spearman correlation coefficients
pairs(model_clean[,vars])
ggpairs(
  model_clean[,vars],
  lower=list(continuous=wrap("points",alpha=0.5)),  
  upper=list(continuous=wrap("cor",method="spearman")),
  diag=list(continuous="densityDiag")  
)

  # Colineality 
modelo_vif<-lm(rec_value~ssb_val+shannon_females,data=model_clean)
vif(modelo_vif) 

```


## Multiple lineal model check 
```{r echo=FALSE, message=TRUE, warning=FALSE, paged.print=FALSE}
lm1<-lm(rec_value~ssb_val+L50_females+shannon_females_s1+shannon_females_s2
        +shannon_females_s3+sst+amo,data=model_clean)
summary(lm1)
vif(lm1) # Multicolineality
par(mfrow=c(2,2))
plot(lm1)
shapiro.test(resid(lm1)) # Normality of the residuals
acf(resid(lm1))
pacf(resid(lm1))
ncvTest(lm1) # Breusch-Pagan Test for homocedasticity

```


### GAM modelling ###

## Variable selection and model fit

```{r, message=FALSE, warning=FALSE, paged.print=FALSE}
p<-gam(rec_value~ssb_val,data=model_clean)
p1<-gam(rec_value~ssb_val+L50_females,data=model_clean)
p2<-gam(rec_value~ssb_val+s(L50_females),data=model_clean)
p3<-gam(rec_value~ssb_val+s(L50_females)+s(shannon_females_s1),data=model_clean)
p4<-gam(rec_value~ssb_val+s(L50_females)+s(shannon_females_s1)+
          s(shannon_females_s2),data=model_clean)
p5<-gam(rec_value~ssb_val+s(L50_females)+s(shannon_females_s1)+s(shannon_females_s2)
       +s(shannon_females_s3),data=model_clean)
p6<-gam(rec_value~ssb_val+s(L50_females)+s(shannon_females_s1)+s(shannon_females_s2)
       +s(shannon_females_s3)+s(shannon_females_s4),data=model_clean)
p7<-gam(rec_value~ssb_val+s(L50_females)+s(shannon_females_s1)+s(shannon_females_s2)
       +s(shannon_females_s3)+s(shannon_females_s4)+s(nao),data=model_clean)
p8<-gam(rec_value~ssb_val+s(L50_females)+s(shannon_females_s1)+s(shannon_females_s2)
       +s(shannon_females_s3)+s(shannon_females_s4)+s(sst)+s(nao),data=model_clean)


u2<-gam(rec_value~ssb_val+L50_females+s(shannon_females_s1,bs="cr",k=4),data=model_clean)
u3<-gam(rec_value~ssb_val+L50_females+s(shannon_females_s1,bs="cr",k=4)+
          s(shannon_females_s3,bs ="cr",k=4),data=model_clean)
u4<-gam(rec_value~ssb_val+L50_females+s(shannon_females_s1,bs="cr",k=4)+
          s(shannon_females_s3,bs="cr",k=4)+s(nao,bs="cr",k=4),data = model_clean)
u5<-gam(rec_value~ssb_val+L50_females+s(shannon_females_s1,bs="cr",k=4)+s(shannon_females_s2,bs="cr",k=4)+
            s(shannon_females_s3,bs="cr",k=4)+s(nao,bs="cr",k=4),data=model_clean)

AIC(u2,u3,u4,u5)
summary(u4)$sp.criterion 
summary(u4)$r.sq
  #anova(p4, u4, test = "Chisq")

```

## Final model validation

```{r echo=FALSE, message=TRUE, warning=FALSE, paged.print=FALSE}
u4<-gam(rec_value~ssb_val+L50_females+s(shannon_females_s1,bs="cr",k=4)+
          s(shannon_females_s3,bs="cr",k=4)+s(nao,bs="cr",k=4),data = model_clean)

summary(u4)
plot(u4, pages=1)
gam.check(u4) 
draw(u4)

qqnorm(resid(u4))
qqline(resid(u4))
shapiro.test(resid(u4))
plot(fitted(u4),resid(u4))
abline(h=0,col="red")

acf(resid(u4),lag.max=38,main="ACF")
pacf(resid(u4),lag.max =38,main="PACF")

Box.test(resid(u4),lag=10,type="Ljung-Box")
adfTest(resid(u4),lag=1) 
kpss.test(resid(u4),lshort=FALSE)
t.test(resid(u4),mu=0)
jarque.bera.test(resid(u4))

res <- resid(u4)
resp<-predict(u4)
plot(res~resp,type="p",xlab="Predichos",ylab="Residuos")

# ARIMA for temporal dependecy
arma_res<-auto.arima(resid(u4),stationary=FALSE,trace=TRUE,seasonal=FALSE,
                     approximation=FALSE,stepwise=TRUE)
(arma_res)
summary(arma_res)
checkresiduals(arma_res)

```


## Model plots

```{r}
# Partial effects
plots<-draw(u4,residuals=FALSE,rug=TRUE,draw=FALSE)
plots_titled<-Map(function(p,title) {
  p+
    theme_classic(base_size=12)+
    labs(title=title)+
    theme(axis.title=element_blank())
},plots,c("s(H´season 1)","S(H´season 3)","s(NAO)"))

final_plot<-wrap_plots(plots_titled,ncol=2)

final_plot<-final_plot+plot_layout(guides="collect")&
  theme_classic(base_size=12)&theme(axis.title.y=element_text(angle=90,vjust=1,size=14)
  )
print(final_plot)

# Increase in deviance explained plot
dev_exp<-c(summary(u1)$dev.expl,summary(u2)$dev.expl,summary(u3)$dev.expl,summary(u4)$dev.expl)

incremento<-c(NA,diff(dev_exp))
labels_incremento<-c("",paste0("\u2206",round(incremento[-1]* 100,1),"%"))
nombres_modelos<-c("SSB+L50","+H\u2032 s1","+H\u2032 s3","+NAO")

df_modelos<-data.frame(Modelo=factor(nombres_modelos,levels=nombres_modelos),
  Deviance=dev_exp,Incremento=labels_incremento)

ggplot(df_modelos,aes(x=Modelo,y=Deviance))+
  geom_bar(stat="identity",fill="#C75B4A",alpha= 0.5)+
  geom_text(aes(label=Incremento),vjust=-0.5,size=4)+
  labs(y="Deviance Explained (%)",x="Stepwise Inclusion")+
  theme_classic(base_size=14) +
  theme(axis.text.x=element_text(face="italic")
)

```


## Temporal tendency of all variables

```{r}
min_year<-min(model_clean$year)
max_year<-max(model_clean$year)
clean_x_axis<-theme(axis.title.x=element_blank(),axis.text.x=element_blank())

p1<-ggplot(model_clean,aes(x=yea,y=rec_value))+
  geom_ribbon(aes(ymin=rec_low,ymax=rec_upp),fill="lightblue",alpha=0.3)+
  geom_line(color="#08306B")+theme_classic()+labs(title="",y="R")+
  theme(axis.title.y=element_text(size=9))+
  scale_x_continuous(limits=c(min_year,max_year),breaks=seq(min_year,max_year,by=5))+
  clean_x_axis

p2<-ggplot(model_clean,aes(x=year,y=ssb_val))+
  geom_ribbon(aes(ymin=ssb_low,ymax=ssb_upp),fill="lightblue",alpha=0.3)+
  geom_line(color="#5BAA9F")+theme_classic()+labs(y="SSB")+
  theme(axis.title.y=element_text(size=9))+
  scale_x_continuous(limits=c(min_year,max_year),breaks=seq(min_year,max_year,by=5))+
  clean_x_axis

p3<-ggplot(model_clean,aes(x=yea,y=L50_females))+
  geom_line(color="#A4C882")+theme_classic()+
  labs(y = expression(L[50]))+theme(axis.title.y=element_text(size=9))+
  scale_x_continuous(limits=c(min_year,max_year),breaks=seq(min_year,max_year,by=5))+
  clean_x_axis

p4<-ggplot(model_clean,aes(x=year,y=nao))+
  geom_line(color="#C3B935")+theme_classic()+labs(x="",y="NAO")+
  theme(axis.title.y=element_text(size=9))+
  scale_x_continuous(limits=c(min_year,max_year),breaks=seq(min_year,max_year,by=5))+

p5<-ggplot(model_clean,aes(x=year,y=shannon_females_s1))+
  geom_line(color="#D29B6E")+theme_classic()+labs(y="H´season 1")+
  theme(axis.title.y=element_text(size=9))+
  scale_x_continuous(limits=c(min_year,max_year),breaks=seq(min_year,max_year,by=5))+
  scale_y_continuous(labels=scales::number_format(accuracy=0.1))+ 
  clean_x_axis

p6<-ggplot(model_clean,aes(x=year,y=shannon_females_s2))+
  geom_line(color="#8B2E25")+theme_classic()+labs(y="H´season 2")+
  theme(axis.title.y=element_text(size=9))+
  scale_x_continuous(limits=c(min_year,max_year),breaks=seq(min_year,max_year,by=5))+
  clean_x_axis

p7<-ggplot(model_clean,aes(x=year,y=shannon_females_s3))+
  geom_line(color="#A97C91")+theme_classic()+
  labs(x="",y="H´season 3")+theme(axis.title.y=element_text(size=9))+
  scale_x_continuous(limits=c(min_year,max_year),breaks=seq(min_year,max_year,by=5))+ 
  clean_x_axis

p8<-ggplot(model_clean,aes(x=year,y=shannon_females_s4))+
  geom_line(color="#E7B6B7")+theme_classic()+labs(x="",y="H´season 4")+
  theme(axis.title.y=element_text(size=9))+
  scale_x_continuous(limits=c(min_year,max_year),breaks= eq(min_year,max_year,by=5))

p1+p2+p3+p4+plot_layout(ncol=1)
p5+p6+p7+p8+plot_layout(ncol=1)

```
